FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY utils ./utils
COPY nuclei/. .

# RUN export no_proxy="localhost"

CMD ["python", "app_consumer.py"]
