FROM python:3.11-slim

WORKDIR /app

COPY nuclei/. .
COPY utils ./utils
RUN pip install --no-cache-dir -r requirements.txt

# Download the onnx and TensorRT model weight
RUN pip install gdown
RUN mkdir -p /app/ckpts/nuclei-yolov8-lung
RUN gdown 1TZhdmUfVe2Q78Vvu4Ex75Qt5geh0SsuZ -O /app/ckpts/nuclei-yolov8-lung/best.onnx
# RUN gdown 1q8KWSgxUZkv2Py1kFb5D-kL3mh2YcfRj -O /app/ckpts/nuclei-yolov8-lung/best.engine

# RUN export no_proxy="localhost"

CMD ["python", "app_consumer.py", "yolov8-lung"]
