FROM python:3.11-slim

WORKDIR /app

COPY nuclei/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY nuclei/. .
COPY utils ./utils

# RUN export no_proxy="localhost"

# gunicorn app_producer:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9021
CMD ["gunicorn", "app_producer:app", "--workers", "8", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:9030"]
