FROM python:3.11-slim

WORKDIR /app

COPY segmentation/requirements.txt .
COPY segmentation/requirements_worker.txt .
RUN pip install --no-cache-dir -r requirements_worker.txt
RUN pip uninstall -y opencv-python
RUN pip install --no-cache-dir -r requirements.txt
COPY segmentation/. .
COPY utils ./utils

# gunicorn app_joint:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:9050
CMD ["gunicorn", "app_joint:app", "--workers", "8", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:9050"]
